services:
  - type: web
    name: video-chat-backend
    runtime: python
    repo: https://github.com/ABDULHODIY1/WebHoookDjango.git
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn randomchat.asgi:application --host 0.0.0.0 --port 10000
envVars:
  - key: REDIS_URL
    value: redis://red-d08eujp5pdvs739o9tq0:6379/0

